(require 'smartchr)
(global-set-key (kbd "{") (smartchr '("{`!!'}" "{")))
(global-set-key (kbd "(") (smartchr '("(`!!')" "(")))
(global-set-key (kbd "[") (smartchr '("[`!!']" "[")))
(global-set-key (kbd "\"") (smartchr '("\"`!!'\"" "\"")))
(global-set-key (kbd "\'") (smartchr '("\'`!!'\'" "\'")))
(global-set-key (kbd "`") (smartchr '("``!!'`" "`")))
